import { Container, Button } from "react-bootstrap";
import { useEffect, useState } from "react";
import Table from 'react-bootstrap/Table';
import { fetchDonors } from "../../Services/DonorService";
import { updateDonorAppointment } from "../../Services/AppointmentService";

export function AdminRequestList() {
    const [request, setRequest] = useState([]);

    async function populateDonorsState() {
        try {
            const data = await fetchDonors();
            console.log(data.appointmentGender);
            setRequest(data.Donor)
        } catch (error) {
            console.log(error);
        }
    }
    useEffect(() => {
        populateDonorsState();
    }, []);

    const approveAppointment= async (donor)=>{
        try {
            await updateDonorAppointment(donor);
            populateDonorsState();
        } catch (error) {
            console.log(error);
        }
    };

    return (

        <Container >

            <h1 className="mt=5">Request for Blood donation</h1>
            {request.length !== 0 ? <Table responsive striped bordered hover variant="light">
                <thead>
                    <tr>
                        <th>Generated By</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Date</th>
                        <th>Gender</th>
                        <th>PhoneNumber</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody> {/* we have create a map which fetch every request form donor table */}
                    {
                        request.map((donor) => {
                            if (donor.appointmentName !== '') {
                                return (

                                    <tr key={donor.email}>

                                        <td>{donor.name}</td>
                                        <td>{donor.appointmentName}</td>
                                        <td>{donor.appointmentEmail}</td>
                                        <td>{donor.appointmentDate}</td>
                                        <td>{donor.appointmentGender}</td>
                                        <td>{donor.appointmentPhoneNumber}</td>
                                        <td>{donor.appointmentTime}</td>
                                        <td>
                                            <Button variant="success" onClick={()=>approveAppointment(donor)} >{donor.appointmentStatus ? "Approved" : "Approve"}</Button>
                                            
                                        </td>
                                    </tr>
                                )
                            }
                        })
                    }
                </tbody>
            </Table> : <p>No request for blood donation</p>}

        </Container >


    );
}