import { Container, Button } from "react-bootstrap";
import { useEffect, useState } from "react";
import Table from 'react-bootstrap/Table';
import { fetchDonors } from "../../Services/DonorService";

export function AdminRequestList() {
    const [request, setRequest] = useState([]);

    async function populateDonorsState() {
        try {
            const data = await fetchDonors();
            console.log(data)
            setRequest(data.Donor)
        } catch (error) {
            console.log(error);
        }
    }
    useEffect(() => {
        populateDonorsState();
    }, []);
    return (

        <Container >

            <h1 className="mt=5">Request for Blood donation</h1>
            {request.length !== 0 ? <Table responsive striped bordered hover variant="light">
                <thead>
                    <tr>
                        <th>Generated By</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Date</th>
                        <th>Gender</th>
                        <th>PhoneNumber</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody> {/* we have create a map which fetch every request form donor table */}
                    {
                        request.map((d) => {
                            console.log(d);
                            if (d.appointmentName !== '') {
                                return (

                                    <tr>

                                        <td>{d.name}</td>
                                        <td>{d.appointmentName}</td>
                                        <td>{d.appointmentEmail}</td>
                                        <td>{d.appointmentDate}</td>
                                        <td>{d.appointmentGender}</td>
                                        <td>{d.appointmentPhoneNumber}</td>
                                        <td>{d.appointmentTime}</td>
                                        <td>
                                            <Button variant="success" >Approve</Button>
                                            
                                        </td>
                                    </tr>
                                )
                            }
                        })
                    }
                </tbody>
            </Table> : <p>No request for blood donation</p>}

        </Container >


    );
}